server {
    listen 80;
    listen [::]:80;

    server_name localhost;

    root /site/public;
    index index.php index.html;

    ## Turn off file upload limit by setting client body size to 0
    client_max_body_size 0;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }


    location ~ \.php$ {
        #include snippets/fastcgi-php.conf;
        #fastcgi_pass unix:/run/php/php7.4-fpm.sock;
        fastcgi_pass ocl-site:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_read_timeout 300;
    }

    location ~ /\.ht {
        deny all;
    }

   error_log /var/log/nginx/error.log;
   access_log /var/log/nginx/access.log;
}